# docker-compose.yml
version: "3.9"
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
