# Dockerfile-backend
FROM  python:3.11-alpine

WORKDIR /app

COPY requirements.txt ./

# Install requirements
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5001

CMD [ "python3", "src/main.py"]
